"""L2 — Per-Session Improvement Loop.

The middle loop: generate code improvements → submit to evaluator →
on approval: apply, checkpoint, update memory.
On rejection: discard, log failure pattern.
"""

import json
import logging
import time
from dataclasses import dataclass, field
from typing import Any, Optional

from rsis.checkpoint import CheckpointManager
from rsis.config import CONFIG
from rsis.evaluator import EvalResult, EvaluatorClient
from rsis.loop_l1 import L1ActionLoop, L1Result, ToolCall
from rsis.telemetry import TelemetryCollector, TelemetryEvent

logger = logging.getLogger(__name__)


@dataclass
class ImprovementCandidate:
    """A candidate improvement generated by L2."""
    description: str
    target_files: list[str]
    diff_or_code: str
    rationale: str
    metadata: dict = field(default_factory=dict)


@dataclass
class L2Result:
    """Outcome of an L2 improvement session."""
    success: bool
    attempts: int = 0
    eval_results: list[EvalResult] = field(default_factory=list)
    candidates: list[ImprovementCandidate] = field(default_factory=list)
    applied: Optional[ImprovementCandidate] = None
    error: Optional[str] = None


class L2ImprovementLoop:
    """Per-session improvement loop with evaluator gate."""

    def __init__(
        self,
        telemetry: TelemetryCollector,
        evaluator: Optional[EvaluatorClient] = None,
        checkpoint_mgr: Optional[CheckpointManager] = None,
        l1_loop: Optional[L1ActionLoop] = None,
    ):
        self.config = CONFIG.l2
        self.telemetry = telemetry
        self.evaluator = evaluator or EvaluatorClient()
        self.checkpoint = checkpoint_mgr or CheckpointManager(CONFIG.workspace_dir)
        self.l1 = l1_loop

    def run_session(self, goal: str) -> L2Result:
        """Run an L2 improvement session.

        Generates up to `max_improvement_attempts` candidates, evaluates each,
        and applies the first one that passes.
        """
        logger.info("L2 session starting — goal: %s", goal[:80])
        self.telemetry.record(TelemetryEvent(
            event_type="l2_start", metadata={"goal": goal},
        ))

        eval_results: list[EvalResult] = []
        candidates: list[ImprovementCandidate] = []
        applied: Optional[ImprovementCandidate] = None

        for attempt in range(1, self.config.max_improvement_attempts + 1):
            logger.info("L2 attempt %d/%d", attempt, self.config.max_improvement_attempts)

            # 1. Generate candidate improvement
            candidate = self._generate_candidate(goal, attempt, eval_results)
            candidates.append(candidate)

            self.telemetry.record(TelemetryEvent(
                event_type="l2_candidate",
                metadata={
                    "attempt": attempt,
                    "target_files": candidate.target_files,
                    "description": candidate.description,
                },
            ))

            # 2. Checkpoint before submitting to evaluator
            if CONFIG.checkpoint_before_mutation:
                self.checkpoint.checkpoint(f"l2-candidate-{attempt}")

            # 3. Submit to evaluator
            eval_result = self.evaluator.evaluate({
                "description": candidate.description,
                "target_files": candidate.target_files,
                "diff": candidate.diff_or_code,
                "rationale": candidate.rationale,
                "attempt": attempt,
                "goal": goal,
            })
            eval_results.append(eval_result)

            self.telemetry.record(TelemetryEvent(
                event_type="l2_evaluation",
                metadata={
                    "attempt": attempt,
                    "decision": eval_result.decision,
                    "score_avg": eval_result.score_avg,
                },
            ))

            # 4. On approval: apply, checkpoint, return
            if eval_result.passed:
                logger.info("L2 candidate approved on attempt %d", attempt)
                self._apply_improvement(candidate)
                self.checkpoint.checkpoint(f"l2-applied-{attempt}-{candidate.description[:30]}")
                applied = candidate
                break
            else:
                logger.info("L2 candidate rejected: %s", eval_result.rationale[:60])

        success = applied is not None

        self.telemetry.record(TelemetryEvent(
            event_type="l2_complete",
            metadata={"success": success, "attempts": len(eval_results)},
        ))

        return L2Result(
            success=success,
            attempts=len(eval_results),
            eval_results=eval_results,
            candidates=candidates,
            applied=applied,
        )

    def _generate_candidate(
        self, goal: str, attempt: int, previous_results: list[EvalResult]
    ) -> ImprovementCandidate:
        """Generate an improvement candidate.

        In production, this uses an LLM to generate code changes based on the
        goal and previous evaluation results. This stub returns a placeholder.
        """
        # In production, this would call an LLM with:
        # - The goal
        # - Previous evaluation results (if any) for iterative refinement
        # - Workspace context (file listing, recent changes)
        return ImprovementCandidate(
            description=f"Stub improvement: {goal[:50]}",
            target_files=["stub.py"],
            diff_or_code="# Generated improvement stub\npass\n",
            rationale="Stub generation — replace with LLM-based codegen.",
            metadata={"attempt": attempt},
        )

    def _apply_improvement(self, candidate: ImprovementCandidate) -> None:
        """Apply an approved improvement to the workspace."""
        logger.info("Applying improvement: %s", candidate.description)
        # In production, this would write the diff to the target files.
        # Stub — just log.
        for f in candidate.target_files:
            logger.info("  Would write to: %s", f)
